language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
env:
    - DJANGO_PACKAGE=https://github.com/django/django/archive/master.zip
install: 'pip install $DJANGO_PACKAGE --use-mirrors && pip install .'
script: make test
